### ISSUE TITLE
Script to make Fig SI1 (distribution plots) is outdated

### ISSUE THREAD

**Issue by TanyaS08** [EnquistLab/trait_bootstrap_ms#27]
It looks like the actual `traitstrap` code being used to generate the figure in `scripts_for_ms_with_traitstrap/3_distribution_figure.R` is outdated if using {traitstrap} 0.1.0. Its calling `trait_impute`... This is probably an easy fix but I'm being lazy/tired so making it a you problem @bmaitner. Or I guess I can look at it later

**Comment by TanyaS08** [comment]
It would be particularly swell if you could make said fixes on the `tidy` branch

**Comment by TanyaS08** [comment]
Okay 1 I changed the file names because we need it tidier!! File can now be found at `scripts/_distribution_figure.R`

**Comment by TanyaS08** [comment]
Also cc'ing @bmaitner because you should also be invested in trying to make this work and it is 'your code' that isn't working after all!

**Comment by bmaitner** [comment]
Technically this isn't a bug, its a user error.  If you had executed the scripts in numerical order, you'd see that in file 1_simulatulations_with_traitstrap.R, the legacy version of traitstrap is installed which includes the old function names.

**Comment by TanyaS08** [comment]
These instructions _should_ be included in the README!!! That’s what it’s for!!!!!!Am 2023-06-02 um 14:48 schrieb Brian Maitner ***@***.***>:﻿
Ok, I added a few lines that check the traitstrap version and install the legacy version if needed.  _distribution_figure.R now runs as expected 🦖

**Comment by TanyaS08** [comment]
eew remind me to not do replies straight from emails they're icky!!!!

**Comment by TanyaS08** [comment]
> Technically this isn't a bug, its a user error. If you had executed the scripts in numerical order, you'd see that in file 1_simulatulations_with_traitstrap.R, the legacy version of traitstrap is installed which includes the old function names.

I think we need to pull that to a different script if we want to bypass any unneeded running of simulation (which I am all for) or I drop that little chink into the _distributions R script (which is repetitive but we're working on good enough practices at this point) 🦕

**Comment by bmaitner** [comment]
@TanyaS08 can we close this now?

**Comment by TanyaS08** [comment]
Damn I thought I had it set up to close with the previous PR!
